// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechLife.CSDLMoiTruong.Data.EF;

#nullable disable

namespace TechLife.CSDLMoiTruong.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250801085606_DeleteTableGiongCayTrong")]
    partial class DeleteTableGiongCayTrong
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechLife.CSDLMoiTruong.Data.Entities.DiaBanAnhHuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreateByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateOnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStatus")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("OrganId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DiaBanAnhHuong");
                });

            modelBuilder.Entity("TechLife.CSDLMoiTruong.Data.Entities.LoaiCayTrong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreateByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateOnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStatus")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("OrganId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LoaiCayTrong");
                });

            modelBuilder.Entity("TechLife.CSDLMoiTruong.Data.Entities.SinhVatGayHai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreateByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateOnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStatus")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoaiCayTrongId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("OrganId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoaiCayTrongId");

                    b.ToTable("SinhVatGayHai");
                });

            modelBuilder.Entity("TechLife.CSDLMoiTruong.Data.Entities.ThoiTiet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreateByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateOnDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DenNgay")
                        .HasColumnType("datetime2");

                    b.Property<double>("DoAmTB")
                        .HasColumnType("float");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStatus")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NgayMua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("NhietDoCaoNhat")
                        .HasColumnType("float");

                    b.Property<double>("NhietDoThapNhat")
                        .HasColumnType("float");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("OrganId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TuNgay")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ThoiTiet");
                });

            modelBuilder.Entity("TechLife.CSDLMoiTruong.Data.Entities.SinhVatGayHai", b =>
                {
                    b.HasOne("TechLife.CSDLMoiTruong.Data.Entities.LoaiCayTrong", "LoaiCayTrong")
                        .WithMany("SinhVatGayHais")
                        .HasForeignKey("LoaiCayTrongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiCayTrong");
                });

            modelBuilder.Entity("TechLife.CSDLMoiTruong.Data.Entities.LoaiCayTrong", b =>
                {
                    b.Navigation("SinhVatGayHais");
                });
#pragma warning restore 612, 618
        }
    }
}
