// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechLife.CSDLMoiTruong.Data.EF;

#nullable disable

namespace TechLife.CSDLMoiTruong.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250803055508_CreateTableSanPhamCongBo")]
    partial class CreateTableSanPhamCongBo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechLife.CSDLMoiTruong.Data.Entities.DiaBanAnhHuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreateByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateOnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStatus")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("OrganId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("DiaBanAnhHuong");
                });

            modelBuilder.Entity("TechLife.CSDLMoiTruong.Data.Entities.DonViCongBo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreateByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateOnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStatus")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("OrganId")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DonViCongBo");
                });

            modelBuilder.Entity("TechLife.CSDLMoiTruong.Data.Entities.LoaiCayTrong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreateByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateOnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStatus")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("OrganId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LoaiCayTrong");
                });

            modelBuilder.Entity("TechLife.CSDLMoiTruong.Data.Entities.SanPhamCongBo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreateByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateOnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DonViCongBoId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStatus")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCongBo")
                        .HasColumnType("datetime2");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("OrganId")
                        .HasColumnType("int");

                    b.Property<string>("SoCongBo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DonViCongBoId");

                    b.ToTable("SanPhamCongBo");
                });

            modelBuilder.Entity("TechLife.CSDLMoiTruong.Data.Entities.SinhVatGayHai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreateByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateOnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStatus")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoaiCayTrongId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("OrganId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoaiCayTrongId");

                    b.ToTable("SinhVatGayHai");
                });

            modelBuilder.Entity("TechLife.CSDLMoiTruong.Data.Entities.SoLieuSinhTruong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CayTrongId")
                        .HasColumnType("int");

                    b.Property<Guid?>("CreateByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateOnDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("DaGieoTrong")
                        .HasColumnType("float");

                    b.Property<DateTime>("DenNgay")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStatus")
                        .HasColumnType("bit");

                    b.Property<double>("KeHoach")
                        .HasColumnType("float");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LoaiCayTrongId")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("OrganId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TuNgay")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LoaiCayTrongId");

                    b.ToTable("SoLieuSinhTruong");
                });

            modelBuilder.Entity("TechLife.CSDLMoiTruong.Data.Entities.ThoiTiet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreateByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateOnDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DenNgay")
                        .HasColumnType("datetime2");

                    b.Property<double>("DoAmTB")
                        .HasColumnType("float");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStatus")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NgayMua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("NhietDoCaoNhat")
                        .HasColumnType("float");

                    b.Property<double>("NhietDoThapNhat")
                        .HasColumnType("float");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("OrganId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TuNgay")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ThoiTiet");
                });

            modelBuilder.Entity("TechLife.CSDLMoiTruong.Data.Entities.TinhHinhGayHaiCayTrong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreateByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateOnDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DenNgay")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiaBanId")
                        .HasColumnType("int");

                    b.Property<double>("DienTichNhiem")
                        .HasColumnType("float");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStatus")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MucDoNhiem")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("OrganId")
                        .HasColumnType("int");

                    b.Property<int>("SinhVatGayHaiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TuNgay")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DiaBanId");

                    b.HasIndex("SinhVatGayHaiId");

                    b.ToTable("TinhHinhGayHaiCayTrong");
                });

            modelBuilder.Entity("TechLife.CSDLMoiTruong.Data.Entities.DiaBanAnhHuong", b =>
                {
                    b.HasOne("TechLife.CSDLMoiTruong.Data.Entities.DiaBanAnhHuong", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TechLife.CSDLMoiTruong.Data.Entities.SanPhamCongBo", b =>
                {
                    b.HasOne("TechLife.CSDLMoiTruong.Data.Entities.DonViCongBo", "DonViCongBo")
                        .WithMany("SanPhamCongBo")
                        .HasForeignKey("DonViCongBoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonViCongBo");
                });

            modelBuilder.Entity("TechLife.CSDLMoiTruong.Data.Entities.SinhVatGayHai", b =>
                {
                    b.HasOne("TechLife.CSDLMoiTruong.Data.Entities.LoaiCayTrong", "LoaiCayTrong")
                        .WithMany("SinhVatGayHais")
                        .HasForeignKey("LoaiCayTrongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiCayTrong");
                });

            modelBuilder.Entity("TechLife.CSDLMoiTruong.Data.Entities.SoLieuSinhTruong", b =>
                {
                    b.HasOne("TechLife.CSDLMoiTruong.Data.Entities.LoaiCayTrong", "LoaiCayTrong")
                        .WithMany("SoLieuSinhTruong")
                        .HasForeignKey("LoaiCayTrongId");

                    b.Navigation("LoaiCayTrong");
                });

            modelBuilder.Entity("TechLife.CSDLMoiTruong.Data.Entities.TinhHinhGayHaiCayTrong", b =>
                {
                    b.HasOne("TechLife.CSDLMoiTruong.Data.Entities.DiaBanAnhHuong", "DiaBan")
                        .WithMany()
                        .HasForeignKey("DiaBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechLife.CSDLMoiTruong.Data.Entities.SinhVatGayHai", "SinhVatGayHai")
                        .WithMany()
                        .HasForeignKey("SinhVatGayHaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaBan");

                    b.Navigation("SinhVatGayHai");
                });

            modelBuilder.Entity("TechLife.CSDLMoiTruong.Data.Entities.DiaBanAnhHuong", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("TechLife.CSDLMoiTruong.Data.Entities.DonViCongBo", b =>
                {
                    b.Navigation("SanPhamCongBo");
                });

            modelBuilder.Entity("TechLife.CSDLMoiTruong.Data.Entities.LoaiCayTrong", b =>
                {
                    b.Navigation("SinhVatGayHais");

                    b.Navigation("SoLieuSinhTruong");
                });
#pragma warning restore 612, 618
        }
    }
}
